### ISSUE TITLE
Allow users to create vector indices with any dimension

### ISSUE THREAD

**Issue by 0xDebabrata** [0xDebabrata/citrus#5]
By default, indices on citrusdb are of 1536 dimensions. Expose APIs to allow developers to set any vector dimension during index creation.

**Comment by ighoshsubho** [comment]
Hey I would like to work on this issue...

**Comment by 0xDebabrata** [comment]
Hey @ighoshsubho 
Thanks for reaching out! Feel free to start working on this. I'd recommend starting to work from the `sqlite-layer` branch. Let me know if you face any issues

**Comment by 0xDebabrata** [comment]
Hi @ighoshsubho!
Are you still planning on working on this one? No worries if not! We'd like to get this closed as soon as possible. If you're busy with something else, I can finish it.

**Comment by 0xDebabrata** [comment]
Cool no problem. Feel free to pick something up later on if you're interested and have some time :)
